#!/usr/bin/env node
// Minimal static build: assembles the root HTML pages from src/pages + src/partials.
// No dependencies. Run `node build.js` (or `npm run build`) after editing anything in src/ or assets/.
const fs = require('fs');
const path = require('path');

const site = {
  name: 'Kamali & Kamali Holding LLC',
  // Set the production origin (no trailing slash) once the domain is known.
  // When set, every page gets a canonical URL and absolute Open Graph URLs.
  siteUrl: '',
  contact: {
    // TODO: replace placeholders with the client's real details (one place, every page updates).
    email: 'partnerships@[domain].com',
    phone: '+971 (0) 2 [XXX XXXX]',
    phoneTel: '+97120000000',
    address: 'PO Box [XXXXXX], Abu Dhabi, United Arab Emirates',
  },
};

const root = __dirname;
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');
const partials = Object.fromEntries(
  fs.readdirSync(path.join(root, 'src/partials')).map((f) => [f.replace(/\.html$/, ''), read('src/partials/' + f)])
);
const layout = read('src/layout.html');

function render(tpl, vars) {
  let out = tpl;
  for (let i = 0; i < 6; i++) {
    const before = out;
    out = out.replace(/\{\{>\s*([\w-]+)\s*\}\}/g, (_, name) => {
      if (!(name in partials)) throw new Error('Unknown partial: ' + name);
      return partials[name];
    });
    out = out.replace(/\{\{\s*([\w.]+)\s*\}\}/g, (m, key) => {
      const v = key.split('.').reduce((o, k) => (o == null ? undefined : o[k]), vars);
      if (v === undefined) throw new Error('Unknown variable: ' + key);
      return String(v);
    });
    if (out === before) break;
  }
  return out;
}

const pagesDir = path.join(root, 'src/pages');
for (const file of fs.readdirSync(pagesDir).filter((f) => f.endsWith('.html'))) {
  const source = read('src/pages/' + file);
  const m = source.match(/^<!--\s*page\s*(\{[\s\S]*?\})\s*-->\s*/);
  if (!m) throw new Error(file + ': missing <!-- page {...} --> header');
  const page = JSON.parse(m[1]);
  const content = source.slice(m[0].length);
  const isHome = file === 'index.html';
  const vars = {
    site,
    contact: site.contact,
    page,
    content,
    year: new Date().getFullYear(),
    home_href: isHome ? '#top' : './index.html',
    home: isHome ? '' : './index.html',
    current_hospitality: file === 'hospitality.html' ? ' aria-current="page"' : '',
    canonical_tags: site.siteUrl
      ? `<link rel="canonical" href="${site.siteUrl}${page.path}">\n<meta property="og:url" content="${site.siteUrl}${page.path}">`
      : '',
  };
  const html = render(layout, vars);
  const banner = `<!-- Generated by build.js from src/pages/${file}. Edit the source and run \`node build.js\`; do not edit this file. -->\n`;
  fs.writeFileSync(path.join(root, file), html.replace('<!DOCTYPE html>\n', '<!DOCTYPE html>\n' + banner));
  console.log('built', file, '(' + page.title + ')');
}
